---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: expense
spec:
  storageClassName: "expense-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: expense
spec:
  selector:
    matchLabels:
      name: db
      tier: App
      owner: Naveen
  serviceName: "db"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        name: db
        tier: App
        owner: Naveen
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: naveen2809/expense-db:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-sc"
      resources:
        requests:
          storage: 1Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: expense
spec:
  clusterIP: None  # Headless Service
  selector:
    name: db
    tier: App
    owner: Naveen
  ports:
  - port: 3306
    targetPort: 3306