apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
  namespace: expense
data:
  DB_HOST: db-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: expense
  # match with service
  labels:
    name: be
    tier: App
    owner: Naveen
spec:
  selector:
    # need t match with template
    matchLabels:
      name: be
      tier: App
      owner: Naveen 
  template:
    metadata:
      labels:
        name: be
        tier: App
        owner: Naveen
    spec:
      containers:
      - name: be
        image: naveen2809/expense-be:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: be-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: expense
  name: be-svc
spec:
  selector:
    name: be
    tier: App
    owner: Naveen
  ports:
  - port: 8080
    targetPort: 8080