# kubectl apply -f 00.pod.yaml
# kubectl get pods
# kubectl describe pod nginx
# kubectl delete -f 00.pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80