# kubectl apply -f 04.env.yaml
# kubectl get pods
# kubectl exec -it env-test -- bash
# kubectl delete -f 04.env.yaml


apiVersion: v1
kind: Pod
metadata:
  name: env-test
  labels:
    name: env-test
spec:
  containers:
  - name: env-test
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20hours'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80