# kubectl apply -f 11.service-test.yaml
# kubectl get svc -o wide
# kubectl get pods -o wide
# kubectl exec -it nginx-pod -- bash
# root@nginx-pod:/# curl http://nginx-service
# kubectl delete -f 11.service-test.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
    owner: nk
    component: fe
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx
    owner: nk
    component: fe
    environment: dev
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: service-test
  labels:
    name: service-test
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80