# kubectl apply -f 13.service-lb.yaml
# kubectl get svc -o wide
# kubectl get pods -o wide
# http://ab283a0214ecc42d79ef407d5c742bb9-986522960.us-east-1.elb.amazonaws.com/
# kubectl delete -f 13.service-lb.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
    owner: nk
    component: fe
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    name: nginx
    owner: nk
    component: fe
    environment: dev
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32294