# kubectl exec -it debug -- sh
# telnet db-svc 3306
# telnet be-svc 8080
# telnet fe-svc 80

apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: expense
  labels:
    name: debug
spec:
  containers:
  - name: debug
    image: joindevops/debug:v1.0
