# eksctl create cluster --config-file=EKS.yaml
# eksctl delete cluster --config-file=EKS.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster
  region: us-east-1

managedNodeGroups:
# `instanceType` defaults to [`m5.large`]
- name: expense
  desiredCapacity: 3
  spot: true