# Admin will create Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-sc
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer