kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
  labels:
    app: app1
    purpose: ingress
spec:
  selector:
    matchLabels:
      app: app1
      purpose: ingress
  template:
    metadata:
      labels:
        app: app1
        purpose: ingress
    spec:
      containers:
      - name: app1
        image: joindevops/app1:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    # this annotation is useful to keep only ALB under expense group. if you don't give this it will create another ALB.
    alb.ingress.kubernetes.io/group.name: expense
spec:
  ingressClassName: alb
  rules:
  - host: "app1.step-into-iot.cloud" # ALB Rule
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1 # ALB Target group
            port:
              number: 80